# Generated by Django 5.0.3 on 2024-08-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='user_pdfs/'),
        ),
    ]
